name: iOS build

on:
  push:
    paths:
    - 'self-care-assistant-ios/**'
    - '.github/workflows/ios-build.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: self-care-assistant-ios/Self-Care Assistant.xcodeproj
          p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: self-care-assistant-ios/Self-Care Assistant.xcworkspace

